### ISSUE TITLE
Plotting a scatter plot between model vs observed 

### ISSUE THREAD

**Issue by halima1993** [MagicForrest/DGVMTools#57]
Hey Matthew, hope you are well this time of year. I wanted to ask that I would like to plot a scatterplot between MODIS and modelled data. DGVMTools does include this code I have noticed :
```
plotScatterComparison(input.CLayers, run.ids = NULL, run.labels = NULL,
  wrap = TRUE, facet.labels = NULL, xlim = NULL, ylim = NULL,
  xlab = NULL, ylab = NULL, text.multiplier = NULL,
  showFitLine = TRUE, showStats = TRUE, alpha = 0.05,
  text.size = 6)
```
However even though I have GPP variable in my modelled output files (which I do create a raster file through `promotetoRaster`), and I have MODIS GPP as a raster file downloaded from a website. I am not able to understand how can I insert these rasters into the plotScatterComparison code. Kindly guide me! Thank you.

**Comment by MagicForrest** [comment]
Hi Halima,

Did you solve this?  In this case I think it might actually be easier to convert your model output to Raster and plot using other R tools.  I want to make using MODIS GPP easy to compare in DGVMTools, but I haven't done it yet...

**Comment by MagicForrest** [comment]
Closing since DGVMTools should not be responsible for making scatter plots directly from raster objects.  But, the new development for the general NetCDF Format should make it easier to read any netCDF file into DGVMTools as a Field object and therefore make scatter plots (or any other type of plots), with it.
