### ISSUE TITLE
Smith 2014 biomization

### ISSUE THREAD

**Issue by lukasbaumbach** [MagicForrest/DGVMTools#63]
Hi Matt!

I looked at your biome classification (had to translate it to Python for my purposes) and noticed a few discrepancies between your code and Smith's (2014) scheme. For example Smith uses maximum LAI of the growing season for all LAI references, whereas - at least as I understood - your code uses the average yearly LPJ-GUESS output "lai.out" for that. This could be particularly important for seasonal forest, where LAI fluctuations are high throughout the year (better use "mlai.out" and average the maxima of each year?).
Additionally some thresholds seemed to be different (although your version is clearer than Smith on that):
-  Boreal biomes: 
_Smith_: LAItree fraction boreal > 0.8
_DGVMTools_: LAItree fraction boreal > 0.5
- Temperate/Boreal Mixed Forest:
_Smith_: LAItree > 2.5 (this is the same as Temperate mixed forest, strange)
_DGVMTools_: 0.2 > LAItree fraction boreal > 0.8 & 0.2 > LAItree fraction temperate > 0.8
- Arctic/alpine Tundra:
_Smith_: LAItotal > 0.2 & LAItree < 0.5
_DGVMTools_: LAItotal > 0.5 & LAItree < 0.5

Just wondering if there where errata in Smith or typos in DGVMTools.
Best,
Lukas

**Comment by MagicForrest** [comment]
Hi Lukas,

On your first point, don't worry, lai.out *is* the maximum over the year.  As for the differences.

* Boreal biomes - oops that is a bug, I'll correct it.
* Temperate/Boreal biomes - that is an errata to the paper I got from Lund (I'll email you the source script from them)
* Tundra - that is a bug from me, it should be total > 0.2.  They also have the condition "tree < 0.5 * grass" which I appear to have omitted.  I'll add it now.

And anything else left over the just classify as desert (which makes the existing) desert criteria redundant, but anyways...

It is a tricky thing, since the script and the table in the paper don't quite add up.  I was confused before.  But now I think I will follow the script exactly and maybe just make a note in DGVMTools.

Cheers,

M@

**Comment by MagicForrest** [comment]
Alright, implemented in the bugfix and dev branches.  And the plots are nicer, thanks for bringing it to my attention.  I'll close this now.

**Comment by lukasbaumbach** [comment]
Thanks for clarifying! Now that I saw the original script, indeed there are some differences to the paper (e.g. the script also applies > 0.8 for temperate biomes). Anyways, at least your version is consistent now :)
